package gov.customs.rule.data;

// Generated Aug 6, 2015 1:59:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * EmsAlcWork generated by hbm2java
 */
public class EmsAlcWork implements java.io.Serializable {

	private EmsAlcWorkId id;
	private Date createDate;
	private String customsCode;
	private String procPos;
	private String procEr;
	private String prevPos;
	private String prevEr;
	private String procFlag;
	private String emsNoBase;
	private String subId;
	private String listFlag;
	private BigDecimal listMin;
	private String versionMin;
	private BigDecimal listMax;
	private String versionMax;
	private String checkFlag;
	private String msgId;

	public EmsAlcWork() {
	}

	public EmsAlcWork(EmsAlcWorkId id) {
		this.id = id;
	}

	public EmsAlcWork(EmsAlcWorkId id, Date createDate, String customsCode,
			String procPos, String procEr, String prevPos, String prevEr,
			String procFlag, String emsNoBase, String subId, String listFlag,
			BigDecimal listMin, String versionMin, BigDecimal listMax,
			String versionMax, String checkFlag, String msgId) {
		this.id = id;
		this.createDate = createDate;
		this.customsCode = customsCode;
		this.procPos = procPos;
		this.procEr = procEr;
		this.prevPos = prevPos;
		this.prevEr = prevEr;
		this.procFlag = procFlag;
		this.emsNoBase = emsNoBase;
		this.subId = subId;
		this.listFlag = listFlag;
		this.listMin = listMin;
		this.versionMin = versionMin;
		this.listMax = listMax;
		this.versionMax = versionMax;
		this.checkFlag = checkFlag;
		this.msgId = msgId;
	}

	public EmsAlcWorkId getId() {
		return this.id;
	}

	public void setId(EmsAlcWorkId id) {
		this.id = id;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCustomsCode() {
		return this.customsCode;
	}

	public void setCustomsCode(String customsCode) {
		this.customsCode = customsCode;
	}

	public String getProcPos() {
		return this.procPos;
	}

	public void setProcPos(String procPos) {
		this.procPos = procPos;
	}

	public String getProcEr() {
		return this.procEr;
	}

	public void setProcEr(String procEr) {
		this.procEr = procEr;
	}

	public String getPrevPos() {
		return this.prevPos;
	}

	public void setPrevPos(String prevPos) {
		this.prevPos = prevPos;
	}

	public String getPrevEr() {
		return this.prevEr;
	}

	public void setPrevEr(String prevEr) {
		this.prevEr = prevEr;
	}

	public String getProcFlag() {
		return this.procFlag;
	}

	public void setProcFlag(String procFlag) {
		this.procFlag = procFlag;
	}

	public String getEmsNoBase() {
		return this.emsNoBase;
	}

	public void setEmsNoBase(String emsNoBase) {
		this.emsNoBase = emsNoBase;
	}

	public String getSubId() {
		return this.subId;
	}

	public void setSubId(String subId) {
		this.subId = subId;
	}

	public String getListFlag() {
		return this.listFlag;
	}

	public void setListFlag(String listFlag) {
		this.listFlag = listFlag;
	}

	public BigDecimal getListMin() {
		return this.listMin;
	}

	public void setListMin(BigDecimal listMin) {
		this.listMin = listMin;
	}

	public String getVersionMin() {
		return this.versionMin;
	}

	public void setVersionMin(String versionMin) {
		this.versionMin = versionMin;
	}

	public BigDecimal getListMax() {
		return this.listMax;
	}

	public void setListMax(BigDecimal listMax) {
		this.listMax = listMax;
	}

	public String getVersionMax() {
		return this.versionMax;
	}

	public void setVersionMax(String versionMax) {
		this.versionMax = versionMax;
	}

	public String getCheckFlag() {
		return this.checkFlag;
	}

	public void setCheckFlag(String checkFlag) {
		this.checkFlag = checkFlag;
	}

	public String getMsgId() {
		return this.msgId;
	}

	public void setMsgId(String msgId) {
		this.msgId = msgId;
	}

}
