package gov.customs.rule.data;

// Generated Aug 6, 2015 1:59:26 PM by Hibernate Tools 3.4.0.CR1

/**
 * EmsAlcWorkId generated by hbm2java
 */
public class EmsAlcWorkId implements java.io.Serializable {

	private String emsNo;
	private String stepId;

	public EmsAlcWorkId() {
	}

	public EmsAlcWorkId(String emsNo, String stepId) {
		this.emsNo = emsNo;
		this.stepId = stepId;
	}

	public String getEmsNo() {
		return this.emsNo;
	}

	public void setEmsNo(String emsNo) {
		this.emsNo = emsNo;
	}

	public String getStepId() {
		return this.stepId;
	}

	public void setStepId(String stepId) {
		this.stepId = stepId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmsAlcWorkId))
			return false;
		EmsAlcWorkId castOther = (EmsAlcWorkId) other;

		return ((this.getEmsNo() == castOther.getEmsNo()) || (this.getEmsNo() != null
				&& castOther.getEmsNo() != null && this.getEmsNo().equals(
				castOther.getEmsNo())))
				&& ((this.getStepId() == castOther.getStepId()) || (this
						.getStepId() != null && castOther.getStepId() != null && this
						.getStepId().equals(castOther.getStepId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getEmsNo() == null ? 0 : this.getEmsNo().hashCode());
		result = 37 * result
				+ (getStepId() == null ? 0 : this.getStepId().hashCode());
		return result;
	}

}
