package gov.customs.rule.data;

// Generated Aug 6, 2015 1:59:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * EmsHeadId generated by hbm2java
 */
public class EmsHeadId implements java.io.Serializable {

	private String emsNo;
	private BigDecimal modifyTimes;

	public EmsHeadId() {
	}

	public EmsHeadId(String emsNo, BigDecimal modifyTimes) {
		this.emsNo = emsNo;
		this.modifyTimes = modifyTimes;
	}

	public String getEmsNo() {
		return this.emsNo;
	}

	public void setEmsNo(String emsNo) {
		this.emsNo = emsNo;
	}

	public BigDecimal getModifyTimes() {
		return this.modifyTimes;
	}

	public void setModifyTimes(BigDecimal modifyTimes) {
		this.modifyTimes = modifyTimes;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmsHeadId))
			return false;
		EmsHeadId castOther = (EmsHeadId) other;

		return ((this.getEmsNo() == castOther.getEmsNo()) || (this.getEmsNo() != null
				&& castOther.getEmsNo() != null && this.getEmsNo().equals(
				castOther.getEmsNo())))
				&& ((this.getModifyTimes() == castOther.getModifyTimes()) || (this
						.getModifyTimes() != null
						&& castOther.getModifyTimes() != null && this
						.getModifyTimes().equals(castOther.getModifyTimes())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getEmsNo() == null ? 0 : this.getEmsNo().hashCode());
		result = 37
				* result
				+ (getModifyTimes() == null ? 0 : this.getModifyTimes()
						.hashCode());
		return result;
	}

}
