package gov.customs.rule.data;

// Generated Aug 6, 2015 1:59:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * EmsHead generated by hbm2java
 */
public class EmsHead implements java.io.Serializable {

	private EmsHeadId id;
	private String preEmsNo;
	private String copEmsNo;
	private String tradeCode;
	private String tradeName;
	private String houseNo;
	private String ownerCode;
	private String ownerName;
	private String ownerType;
	private String declareErType;
	private String declareCode;
	private String declareName;
	private String districtCode;
	private String address;
	private String phone;
	private String emsType;
	private String declareType;
	private String appendType;
	private String investMode;
	private String tradeMode;
	private Date beginDate;
	private Date endDate;
	private BigDecimal imgAmount;
	private BigDecimal exgAmount;
	private BigDecimal imgWeight;
	private BigDecimal exgWeight;
	private BigDecimal storeVol;
	private BigDecimal storeArea;
	private BigDecimal imgItems;
	private BigDecimal exgItems;
	private String emsApprNo;
	private String licenseNo;
	private String lastEmsNo;
	private String corrEmsNo;
	private String contrNo;
	private String idCard;
	private String idCardPwd;
	private String note1;
	private String note2;
	private BigDecimal investAmount;
	private BigDecimal noteAmount;
	private BigDecimal noteQty;
	private String note;
	private Date inputDate;
	private String inputEr;
	private Date declareDate;
	private String emsApprMark;
	private String emsCertify;
	private BigDecimal productRatio;
	private String modifyMark;
	private String declareMark;
	private String chkMark;
	private String exeMark;
	private Date newApprDate;
	private Date cngApprDate;
	private Date clearDate;
	private Date signDate;
	private BigDecimal signCopy;
	private Date printDate;
	private String printMark;
	private Date returnDate;
	private String returnMark;
	private String emsAceMark;
	private String h883AceMark;
	private String controlMark;
	private String processMark;
	private String clearMode;
	private BigDecimal clearTerm;
	private String clearMark;
	private BigDecimal clearTimes;
	private String serviceFeeMark;
	private BigDecimal serviceFeeRate;
	private BigDecimal serviceFee;
	private String fileNo;
	private String recorderNo;
	private String documentNo;
	private String masterCustoms;
	private String IEPort;
	private String foreignCoName;
	private String agreeNo;
	private String cutMode;
	private String payMode;
	private String produceType;
	private String contrOut;
	private String messageType;
	private String eportId;
	private String digitalSignMark;
	private String digitalSignLen;
	private String digitalSign;
	private String etlMark;
	private Date IDate;
	private BigDecimal imgedAmount;
	private String clearApprMark;
	private Date clearApplDate;
	private String closeMark;
	private Date closeDate;
	private String checkMark;
	private String checkResult;
	private String foreignMgr;
	private String transMode;
	private String tradeCountry;
	private String equipMode;
	private BigDecimal inRatio;
	private String exCurr;
	private String imCurr;
	private String operMark;
	private BigDecimal factDevAmt;
	private BigDecimal apprImgAmt;
	private BigDecimal apprExgAmt;
	private String closeResult;
	private Date deductDate;
	private String accountFlag;
	private BigDecimal htApprImgAmt;
	private String caseMark;

	public EmsHead() {
	}

	public EmsHead(EmsHeadId id) {
		this.id = id;
	}

	public EmsHead(EmsHeadId id, String preEmsNo, String copEmsNo,
			String tradeCode, String tradeName, String houseNo,
			String ownerCode, String ownerName, String ownerType,
			String declareErType, String declareCode, String declareName,
			String districtCode, String address, String phone, String emsType,
			String declareType, String appendType, String investMode,
			String tradeMode, Date beginDate, Date endDate,
			BigDecimal imgAmount, BigDecimal exgAmount, BigDecimal imgWeight,
			BigDecimal exgWeight, BigDecimal storeVol, BigDecimal storeArea,
			BigDecimal imgItems, BigDecimal exgItems, String emsApprNo,
			String licenseNo, String lastEmsNo, String corrEmsNo,
			String contrNo, String idCard, String idCardPwd, String note1,
			String note2, BigDecimal investAmount, BigDecimal noteAmount,
			BigDecimal noteQty, String note, Date inputDate, String inputEr,
			Date declareDate, String emsApprMark, String emsCertify,
			BigDecimal productRatio, String modifyMark, String declareMark,
			String chkMark, String exeMark, Date newApprDate, Date cngApprDate,
			Date clearDate, Date signDate, BigDecimal signCopy, Date printDate,
			String printMark, Date returnDate, String returnMark,
			String emsAceMark, String h883AceMark, String controlMark,
			String processMark, String clearMode, BigDecimal clearTerm,
			String clearMark, BigDecimal clearTimes, String serviceFeeMark,
			BigDecimal serviceFeeRate, BigDecimal serviceFee, String fileNo,
			String recorderNo, String documentNo, String masterCustoms,
			String IEPort, String foreignCoName, String agreeNo,
			String cutMode, String payMode, String produceType,
			String contrOut, String messageType, String eportId,
			String digitalSignMark, String digitalSignLen, String digitalSign,
			String etlMark, Date IDate, BigDecimal imgedAmount,
			String clearApprMark, Date clearApplDate, String closeMark,
			Date closeDate, String checkMark, String checkResult,
			String foreignMgr, String transMode, String tradeCountry,
			String equipMode, BigDecimal inRatio, String exCurr, String imCurr,
			String operMark, BigDecimal factDevAmt, BigDecimal apprImgAmt,
			BigDecimal apprExgAmt, String closeResult, Date deductDate,
			String accountFlag, BigDecimal htApprImgAmt, String caseMark) {
		this.id = id;
		this.preEmsNo = preEmsNo;
		this.copEmsNo = copEmsNo;
		this.tradeCode = tradeCode;
		this.tradeName = tradeName;
		this.houseNo = houseNo;
		this.ownerCode = ownerCode;
		this.ownerName = ownerName;
		this.ownerType = ownerType;
		this.declareErType = declareErType;
		this.declareCode = declareCode;
		this.declareName = declareName;
		this.districtCode = districtCode;
		this.address = address;
		this.phone = phone;
		this.emsType = emsType;
		this.declareType = declareType;
		this.appendType = appendType;
		this.investMode = investMode;
		this.tradeMode = tradeMode;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.imgAmount = imgAmount;
		this.exgAmount = exgAmount;
		this.imgWeight = imgWeight;
		this.exgWeight = exgWeight;
		this.storeVol = storeVol;
		this.storeArea = storeArea;
		this.imgItems = imgItems;
		this.exgItems = exgItems;
		this.emsApprNo = emsApprNo;
		this.licenseNo = licenseNo;
		this.lastEmsNo = lastEmsNo;
		this.corrEmsNo = corrEmsNo;
		this.contrNo = contrNo;
		this.idCard = idCard;
		this.idCardPwd = idCardPwd;
		this.note1 = note1;
		this.note2 = note2;
		this.investAmount = investAmount;
		this.noteAmount = noteAmount;
		this.noteQty = noteQty;
		this.note = note;
		this.inputDate = inputDate;
		this.inputEr = inputEr;
		this.declareDate = declareDate;
		this.emsApprMark = emsApprMark;
		this.emsCertify = emsCertify;
		this.productRatio = productRatio;
		this.modifyMark = modifyMark;
		this.declareMark = declareMark;
		this.chkMark = chkMark;
		this.exeMark = exeMark;
		this.newApprDate = newApprDate;
		this.cngApprDate = cngApprDate;
		this.clearDate = clearDate;
		this.signDate = signDate;
		this.signCopy = signCopy;
		this.printDate = printDate;
		this.printMark = printMark;
		this.returnDate = returnDate;
		this.returnMark = returnMark;
		this.emsAceMark = emsAceMark;
		this.h883AceMark = h883AceMark;
		this.controlMark = controlMark;
		this.processMark = processMark;
		this.clearMode = clearMode;
		this.clearTerm = clearTerm;
		this.clearMark = clearMark;
		this.clearTimes = clearTimes;
		this.serviceFeeMark = serviceFeeMark;
		this.serviceFeeRate = serviceFeeRate;
		this.serviceFee = serviceFee;
		this.fileNo = fileNo;
		this.recorderNo = recorderNo;
		this.documentNo = documentNo;
		this.masterCustoms = masterCustoms;
		this.IEPort = IEPort;
		this.foreignCoName = foreignCoName;
		this.agreeNo = agreeNo;
		this.cutMode = cutMode;
		this.payMode = payMode;
		this.produceType = produceType;
		this.contrOut = contrOut;
		this.messageType = messageType;
		this.eportId = eportId;
		this.digitalSignMark = digitalSignMark;
		this.digitalSignLen = digitalSignLen;
		this.digitalSign = digitalSign;
		this.etlMark = etlMark;
		this.IDate = IDate;
		this.imgedAmount = imgedAmount;
		this.clearApprMark = clearApprMark;
		this.clearApplDate = clearApplDate;
		this.closeMark = closeMark;
		this.closeDate = closeDate;
		this.checkMark = checkMark;
		this.checkResult = checkResult;
		this.foreignMgr = foreignMgr;
		this.transMode = transMode;
		this.tradeCountry = tradeCountry;
		this.equipMode = equipMode;
		this.inRatio = inRatio;
		this.exCurr = exCurr;
		this.imCurr = imCurr;
		this.operMark = operMark;
		this.factDevAmt = factDevAmt;
		this.apprImgAmt = apprImgAmt;
		this.apprExgAmt = apprExgAmt;
		this.closeResult = closeResult;
		this.deductDate = deductDate;
		this.accountFlag = accountFlag;
		this.htApprImgAmt = htApprImgAmt;
		this.caseMark = caseMark;
	}

	public EmsHeadId getId() {
		return this.id;
	}

	public void setId(EmsHeadId id) {
		this.id = id;
	}

	public String getPreEmsNo() {
		return this.preEmsNo;
	}

	public void setPreEmsNo(String preEmsNo) {
		this.preEmsNo = preEmsNo;
	}

	public String getCopEmsNo() {
		return this.copEmsNo;
	}

	public void setCopEmsNo(String copEmsNo) {
		this.copEmsNo = copEmsNo;
	}

	public String getTradeCode() {
		return this.tradeCode;
	}

	public void setTradeCode(String tradeCode) {
		this.tradeCode = tradeCode;
	}

	public String getTradeName() {
		return this.tradeName;
	}

	public void setTradeName(String tradeName) {
		this.tradeName = tradeName;
	}

	public String getHouseNo() {
		return this.houseNo;
	}

	public void setHouseNo(String houseNo) {
		this.houseNo = houseNo;
	}

	public String getOwnerCode() {
		return this.ownerCode;
	}

	public void setOwnerCode(String ownerCode) {
		this.ownerCode = ownerCode;
	}

	public String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	public String getOwnerType() {
		return this.ownerType;
	}

	public void setOwnerType(String ownerType) {
		this.ownerType = ownerType;
	}

	public String getDeclareErType() {
		return this.declareErType;
	}

	public void setDeclareErType(String declareErType) {
		this.declareErType = declareErType;
	}

	public String getDeclareCode() {
		return this.declareCode;
	}

	public void setDeclareCode(String declareCode) {
		this.declareCode = declareCode;
	}

	public String getDeclareName() {
		return this.declareName;
	}

	public void setDeclareName(String declareName) {
		this.declareName = declareName;
	}

	public String getDistrictCode() {
		return this.districtCode;
	}

	public void setDistrictCode(String districtCode) {
		this.districtCode = districtCode;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmsType() {
		return this.emsType;
	}

	public void setEmsType(String emsType) {
		this.emsType = emsType;
	}

	public String getDeclareType() {
		return this.declareType;
	}

	public void setDeclareType(String declareType) {
		this.declareType = declareType;
	}

	public String getAppendType() {
		return this.appendType;
	}

	public void setAppendType(String appendType) {
		this.appendType = appendType;
	}

	public String getInvestMode() {
		return this.investMode;
	}

	public void setInvestMode(String investMode) {
		this.investMode = investMode;
	}

	public String getTradeMode() {
		return this.tradeMode;
	}

	public void setTradeMode(String tradeMode) {
		this.tradeMode = tradeMode;
	}

	public Date getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public BigDecimal getImgAmount() {
		return this.imgAmount;
	}

	public void setImgAmount(BigDecimal imgAmount) {
		this.imgAmount = imgAmount;
	}

	public BigDecimal getExgAmount() {
		return this.exgAmount;
	}

	public void setExgAmount(BigDecimal exgAmount) {
		this.exgAmount = exgAmount;
	}

	public BigDecimal getImgWeight() {
		return this.imgWeight;
	}

	public void setImgWeight(BigDecimal imgWeight) {
		this.imgWeight = imgWeight;
	}

	public BigDecimal getExgWeight() {
		return this.exgWeight;
	}

	public void setExgWeight(BigDecimal exgWeight) {
		this.exgWeight = exgWeight;
	}

	public BigDecimal getStoreVol() {
		return this.storeVol;
	}

	public void setStoreVol(BigDecimal storeVol) {
		this.storeVol = storeVol;
	}

	public BigDecimal getStoreArea() {
		return this.storeArea;
	}

	public void setStoreArea(BigDecimal storeArea) {
		this.storeArea = storeArea;
	}

	public BigDecimal getImgItems() {
		return this.imgItems;
	}

	public void setImgItems(BigDecimal imgItems) {
		this.imgItems = imgItems;
	}

	public BigDecimal getExgItems() {
		return this.exgItems;
	}

	public void setExgItems(BigDecimal exgItems) {
		this.exgItems = exgItems;
	}

	public String getEmsApprNo() {
		return this.emsApprNo;
	}

	public void setEmsApprNo(String emsApprNo) {
		this.emsApprNo = emsApprNo;
	}

	public String getLicenseNo() {
		return this.licenseNo;
	}

	public void setLicenseNo(String licenseNo) {
		this.licenseNo = licenseNo;
	}

	public String getLastEmsNo() {
		return this.lastEmsNo;
	}

	public void setLastEmsNo(String lastEmsNo) {
		this.lastEmsNo = lastEmsNo;
	}

	public String getCorrEmsNo() {
		return this.corrEmsNo;
	}

	public void setCorrEmsNo(String corrEmsNo) {
		this.corrEmsNo = corrEmsNo;
	}

	public String getContrNo() {
		return this.contrNo;
	}

	public void setContrNo(String contrNo) {
		this.contrNo = contrNo;
	}

	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public String getIdCardPwd() {
		return this.idCardPwd;
	}

	public void setIdCardPwd(String idCardPwd) {
		this.idCardPwd = idCardPwd;
	}

	public String getNote1() {
		return this.note1;
	}

	public void setNote1(String note1) {
		this.note1 = note1;
	}

	public String getNote2() {
		return this.note2;
	}

	public void setNote2(String note2) {
		this.note2 = note2;
	}

	public BigDecimal getInvestAmount() {
		return this.investAmount;
	}

	public void setInvestAmount(BigDecimal investAmount) {
		this.investAmount = investAmount;
	}

	public BigDecimal getNoteAmount() {
		return this.noteAmount;
	}

	public void setNoteAmount(BigDecimal noteAmount) {
		this.noteAmount = noteAmount;
	}

	public BigDecimal getNoteQty() {
		return this.noteQty;
	}

	public void setNoteQty(BigDecimal noteQty) {
		this.noteQty = noteQty;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Date inputDate) {
		this.inputDate = inputDate;
	}

	public String getInputEr() {
		return this.inputEr;
	}

	public void setInputEr(String inputEr) {
		this.inputEr = inputEr;
	}

	public Date getDeclareDate() {
		return this.declareDate;
	}

	public void setDeclareDate(Date declareDate) {
		this.declareDate = declareDate;
	}

	public String getEmsApprMark() {
		return this.emsApprMark;
	}

	public void setEmsApprMark(String emsApprMark) {
		this.emsApprMark = emsApprMark;
	}

	public String getEmsCertify() {
		return this.emsCertify;
	}

	public void setEmsCertify(String emsCertify) {
		this.emsCertify = emsCertify;
	}

	public BigDecimal getProductRatio() {
		return this.productRatio;
	}

	public void setProductRatio(BigDecimal productRatio) {
		this.productRatio = productRatio;
	}

	public String getModifyMark() {
		return this.modifyMark;
	}

	public void setModifyMark(String modifyMark) {
		this.modifyMark = modifyMark;
	}

	public String getDeclareMark() {
		return this.declareMark;
	}

	public void setDeclareMark(String declareMark) {
		this.declareMark = declareMark;
	}

	public String getChkMark() {
		return this.chkMark;
	}

	public void setChkMark(String chkMark) {
		this.chkMark = chkMark;
	}

	public String getExeMark() {
		return this.exeMark;
	}

	public void setExeMark(String exeMark) {
		this.exeMark = exeMark;
	}

	public Date getNewApprDate() {
		return this.newApprDate;
	}

	public void setNewApprDate(Date newApprDate) {
		this.newApprDate = newApprDate;
	}

	public Date getCngApprDate() {
		return this.cngApprDate;
	}

	public void setCngApprDate(Date cngApprDate) {
		this.cngApprDate = cngApprDate;
	}

	public Date getClearDate() {
		return this.clearDate;
	}

	public void setClearDate(Date clearDate) {
		this.clearDate = clearDate;
	}

	public Date getSignDate() {
		return this.signDate;
	}

	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

	public BigDecimal getSignCopy() {
		return this.signCopy;
	}

	public void setSignCopy(BigDecimal signCopy) {
		this.signCopy = signCopy;
	}

	public Date getPrintDate() {
		return this.printDate;
	}

	public void setPrintDate(Date printDate) {
		this.printDate = printDate;
	}

	public String getPrintMark() {
		return this.printMark;
	}

	public void setPrintMark(String printMark) {
		this.printMark = printMark;
	}

	public Date getReturnDate() {
		return this.returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

	public String getReturnMark() {
		return this.returnMark;
	}

	public void setReturnMark(String returnMark) {
		this.returnMark = returnMark;
	}

	public String getEmsAceMark() {
		return this.emsAceMark;
	}

	public void setEmsAceMark(String emsAceMark) {
		this.emsAceMark = emsAceMark;
	}

	public String getH883AceMark() {
		return this.h883AceMark;
	}

	public void setH883AceMark(String h883AceMark) {
		this.h883AceMark = h883AceMark;
	}

	public String getControlMark() {
		return this.controlMark;
	}

	public void setControlMark(String controlMark) {
		this.controlMark = controlMark;
	}

	public String getProcessMark() {
		return this.processMark;
	}

	public void setProcessMark(String processMark) {
		this.processMark = processMark;
	}

	public String getClearMode() {
		return this.clearMode;
	}

	public void setClearMode(String clearMode) {
		this.clearMode = clearMode;
	}

	public BigDecimal getClearTerm() {
		return this.clearTerm;
	}

	public void setClearTerm(BigDecimal clearTerm) {
		this.clearTerm = clearTerm;
	}

	public String getClearMark() {
		return this.clearMark;
	}

	public void setClearMark(String clearMark) {
		this.clearMark = clearMark;
	}

	public BigDecimal getClearTimes() {
		return this.clearTimes;
	}

	public void setClearTimes(BigDecimal clearTimes) {
		this.clearTimes = clearTimes;
	}

	public String getServiceFeeMark() {
		return this.serviceFeeMark;
	}

	public void setServiceFeeMark(String serviceFeeMark) {
		this.serviceFeeMark = serviceFeeMark;
	}

	public BigDecimal getServiceFeeRate() {
		return this.serviceFeeRate;
	}

	public void setServiceFeeRate(BigDecimal serviceFeeRate) {
		this.serviceFeeRate = serviceFeeRate;
	}

	public BigDecimal getServiceFee() {
		return this.serviceFee;
	}

	public void setServiceFee(BigDecimal serviceFee) {
		this.serviceFee = serviceFee;
	}

	public String getFileNo() {
		return this.fileNo;
	}

	public void setFileNo(String fileNo) {
		this.fileNo = fileNo;
	}

	public String getRecorderNo() {
		return this.recorderNo;
	}

	public void setRecorderNo(String recorderNo) {
		this.recorderNo = recorderNo;
	}

	public String getDocumentNo() {
		return this.documentNo;
	}

	public void setDocumentNo(String documentNo) {
		this.documentNo = documentNo;
	}

	public String getMasterCustoms() {
		return this.masterCustoms;
	}

	public void setMasterCustoms(String masterCustoms) {
		this.masterCustoms = masterCustoms;
	}

	public String getIEPort() {
		return this.IEPort;
	}

	public void setIEPort(String IEPort) {
		this.IEPort = IEPort;
	}

	public String getForeignCoName() {
		return this.foreignCoName;
	}

	public void setForeignCoName(String foreignCoName) {
		this.foreignCoName = foreignCoName;
	}

	public String getAgreeNo() {
		return this.agreeNo;
	}

	public void setAgreeNo(String agreeNo) {
		this.agreeNo = agreeNo;
	}

	public String getCutMode() {
		return this.cutMode;
	}

	public void setCutMode(String cutMode) {
		this.cutMode = cutMode;
	}

	public String getPayMode() {
		return this.payMode;
	}

	public void setPayMode(String payMode) {
		this.payMode = payMode;
	}

	public String getProduceType() {
		return this.produceType;
	}

	public void setProduceType(String produceType) {
		this.produceType = produceType;
	}

	public String getContrOut() {
		return this.contrOut;
	}

	public void setContrOut(String contrOut) {
		this.contrOut = contrOut;
	}

	public String getMessageType() {
		return this.messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	public String getEportId() {
		return this.eportId;
	}

	public void setEportId(String eportId) {
		this.eportId = eportId;
	}

	public String getDigitalSignMark() {
		return this.digitalSignMark;
	}

	public void setDigitalSignMark(String digitalSignMark) {
		this.digitalSignMark = digitalSignMark;
	}

	public String getDigitalSignLen() {
		return this.digitalSignLen;
	}

	public void setDigitalSignLen(String digitalSignLen) {
		this.digitalSignLen = digitalSignLen;
	}

	public String getDigitalSign() {
		return this.digitalSign;
	}

	public void setDigitalSign(String digitalSign) {
		this.digitalSign = digitalSign;
	}

	public String getEtlMark() {
		return this.etlMark;
	}

	public void setEtlMark(String etlMark) {
		this.etlMark = etlMark;
	}

	public Date getIDate() {
		return this.IDate;
	}

	public void setIDate(Date IDate) {
		this.IDate = IDate;
	}

	public BigDecimal getImgedAmount() {
		return this.imgedAmount;
	}

	public void setImgedAmount(BigDecimal imgedAmount) {
		this.imgedAmount = imgedAmount;
	}

	public String getClearApprMark() {
		return this.clearApprMark;
	}

	public void setClearApprMark(String clearApprMark) {
		this.clearApprMark = clearApprMark;
	}

	public Date getClearApplDate() {
		return this.clearApplDate;
	}

	public void setClearApplDate(Date clearApplDate) {
		this.clearApplDate = clearApplDate;
	}

	public String getCloseMark() {
		return this.closeMark;
	}

	public void setCloseMark(String closeMark) {
		this.closeMark = closeMark;
	}

	public Date getCloseDate() {
		return this.closeDate;
	}

	public void setCloseDate(Date closeDate) {
		this.closeDate = closeDate;
	}

	public String getCheckMark() {
		return this.checkMark;
	}

	public void setCheckMark(String checkMark) {
		this.checkMark = checkMark;
	}

	public String getCheckResult() {
		return this.checkResult;
	}

	public void setCheckResult(String checkResult) {
		this.checkResult = checkResult;
	}

	public String getForeignMgr() {
		return this.foreignMgr;
	}

	public void setForeignMgr(String foreignMgr) {
		this.foreignMgr = foreignMgr;
	}

	public String getTransMode() {
		return this.transMode;
	}

	public void setTransMode(String transMode) {
		this.transMode = transMode;
	}

	public String getTradeCountry() {
		return this.tradeCountry;
	}

	public void setTradeCountry(String tradeCountry) {
		this.tradeCountry = tradeCountry;
	}

	public String getEquipMode() {
		return this.equipMode;
	}

	public void setEquipMode(String equipMode) {
		this.equipMode = equipMode;
	}

	public BigDecimal getInRatio() {
		return this.inRatio;
	}

	public void setInRatio(BigDecimal inRatio) {
		this.inRatio = inRatio;
	}

	public String getExCurr() {
		return this.exCurr;
	}

	public void setExCurr(String exCurr) {
		this.exCurr = exCurr;
	}

	public String getImCurr() {
		return this.imCurr;
	}

	public void setImCurr(String imCurr) {
		this.imCurr = imCurr;
	}

	public String getOperMark() {
		return this.operMark;
	}

	public void setOperMark(String operMark) {
		this.operMark = operMark;
	}

	public BigDecimal getFactDevAmt() {
		return this.factDevAmt;
	}

	public void setFactDevAmt(BigDecimal factDevAmt) {
		this.factDevAmt = factDevAmt;
	}

	public BigDecimal getApprImgAmt() {
		return this.apprImgAmt;
	}

	public void setApprImgAmt(BigDecimal apprImgAmt) {
		this.apprImgAmt = apprImgAmt;
	}

	public BigDecimal getApprExgAmt() {
		return this.apprExgAmt;
	}

	public void setApprExgAmt(BigDecimal apprExgAmt) {
		this.apprExgAmt = apprExgAmt;
	}

	public String getCloseResult() {
		return this.closeResult;
	}

	public void setCloseResult(String closeResult) {
		this.closeResult = closeResult;
	}

	public Date getDeductDate() {
		return this.deductDate;
	}

	public void setDeductDate(Date deductDate) {
		this.deductDate = deductDate;
	}

	public String getAccountFlag() {
		return this.accountFlag;
	}

	public void setAccountFlag(String accountFlag) {
		this.accountFlag = accountFlag;
	}

	public BigDecimal getHtApprImgAmt() {
		return this.htApprImgAmt;
	}

	public void setHtApprImgAmt(BigDecimal htApprImgAmt) {
		this.htApprImgAmt = htApprImgAmt;
	}

	public String getCaseMark() {
		return this.caseMark;
	}

	public void setCaseMark(String caseMark) {
		this.caseMark = caseMark;
	}

}
