package gov.customs.rule.data;

// Generated Aug 6, 2015 1:59:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * RuleData generated by hbm2java
 */
public class RuleData implements java.io.Serializable {

	private BigDecimal ruleId;
	private String ruleName;
	private String preRuleCond;
	private String ruleCond;
	private String postRuleAction;
	private Boolean isExit;
	private Boolean isLog;
	private String logDesc;
	private Boolean isEstimate;
	private Boolean isShare;
	private Boolean isFeedback;
	private String ruleType;
	private String loopCond;
	private String execKey;
	private String ruleStatus;
	private Date effectiveDate;
	private BigDecimal ruleVersion;
	private BigDecimal serviceDomain;
	private BigDecimal ownerSys;
	private String category;
	private String createPerson;
	private String scene;
	private String customsCode;
	private String note;
	private String businessCode;
	private String hitDesc;
	private String positionDesc;
	private String entityKeys;

	public RuleData() {
	}

	public RuleData(BigDecimal ruleId) {
		this.ruleId = ruleId;
	}

	public RuleData(BigDecimal ruleId, String ruleName, String preRuleCond,
			String ruleCond, String postRuleAction, Boolean isExit,
			Boolean isLog, String logDesc, Boolean isEstimate, Boolean isShare,
			Boolean isFeedback, String ruleType, String loopCond,
			String execKey, String ruleStatus, Date effectiveDate,
			BigDecimal ruleVersion, BigDecimal serviceDomain,
			BigDecimal ownerSys, String category, String createPerson,
			String scene, String customsCode, String note, String businessCode,
			String hitDesc, String positionDesc, String entityKeys) {
		this.ruleId = ruleId;
		this.ruleName = ruleName;
		this.preRuleCond = preRuleCond;
		this.ruleCond = ruleCond;
		this.postRuleAction = postRuleAction;
		this.isExit = isExit;
		this.isLog = isLog;
		this.logDesc = logDesc;
		this.isEstimate = isEstimate;
		this.isShare = isShare;
		this.isFeedback = isFeedback;
		this.ruleType = ruleType;
		this.loopCond = loopCond;
		this.execKey = execKey;
		this.ruleStatus = ruleStatus;
		this.effectiveDate = effectiveDate;
		this.ruleVersion = ruleVersion;
		this.serviceDomain = serviceDomain;
		this.ownerSys = ownerSys;
		this.category = category;
		this.createPerson = createPerson;
		this.scene = scene;
		this.customsCode = customsCode;
		this.note = note;
		this.businessCode = businessCode;
		this.hitDesc = hitDesc;
		this.positionDesc = positionDesc;
		this.entityKeys = entityKeys;
	}

	public BigDecimal getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(BigDecimal ruleId) {
		this.ruleId = ruleId;
	}

	public String getRuleName() {
		return this.ruleName;
	}

	public void setRuleName(String ruleName) {
		this.ruleName = ruleName;
	}

	public String getPreRuleCond() {
		return this.preRuleCond;
	}

	public void setPreRuleCond(String preRuleCond) {
		this.preRuleCond = preRuleCond;
	}

	public String getRuleCond() {
		return this.ruleCond;
	}

	public void setRuleCond(String ruleCond) {
		this.ruleCond = ruleCond;
	}

	public String getPostRuleAction() {
		return this.postRuleAction;
	}

	public void setPostRuleAction(String postRuleAction) {
		this.postRuleAction = postRuleAction;
	}

	public Boolean getIsExit() {
		return this.isExit;
	}

	public void setIsExit(Boolean isExit) {
		this.isExit = isExit;
	}

	public Boolean getIsLog() {
		return this.isLog;
	}

	public void setIsLog(Boolean isLog) {
		this.isLog = isLog;
	}

	public String getLogDesc() {
		return this.logDesc;
	}

	public void setLogDesc(String logDesc) {
		this.logDesc = logDesc;
	}

	public Boolean getIsEstimate() {
		return this.isEstimate;
	}

	public void setIsEstimate(Boolean isEstimate) {
		this.isEstimate = isEstimate;
	}

	public Boolean getIsShare() {
		return this.isShare;
	}

	public void setIsShare(Boolean isShare) {
		this.isShare = isShare;
	}

	public Boolean getIsFeedback() {
		return this.isFeedback;
	}

	public void setIsFeedback(Boolean isFeedback) {
		this.isFeedback = isFeedback;
	}

	public String getRuleType() {
		return this.ruleType;
	}

	public void setRuleType(String ruleType) {
		this.ruleType = ruleType;
	}

	public String getLoopCond() {
		return this.loopCond;
	}

	public void setLoopCond(String loopCond) {
		this.loopCond = loopCond;
	}

	public String getExecKey() {
		return this.execKey;
	}

	public void setExecKey(String execKey) {
		this.execKey = execKey;
	}

	public String getRuleStatus() {
		return this.ruleStatus;
	}

	public void setRuleStatus(String ruleStatus) {
		this.ruleStatus = ruleStatus;
	}

	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	public BigDecimal getRuleVersion() {
		return this.ruleVersion;
	}

	public void setRuleVersion(BigDecimal ruleVersion) {
		this.ruleVersion = ruleVersion;
	}

	public BigDecimal getServiceDomain() {
		return this.serviceDomain;
	}

	public void setServiceDomain(BigDecimal serviceDomain) {
		this.serviceDomain = serviceDomain;
	}

	public BigDecimal getOwnerSys() {
		return this.ownerSys;
	}

	public void setOwnerSys(BigDecimal ownerSys) {
		this.ownerSys = ownerSys;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getCreatePerson() {
		return this.createPerson;
	}

	public void setCreatePerson(String createPerson) {
		this.createPerson = createPerson;
	}

	public String getScene() {
		return this.scene;
	}

	public void setScene(String scene) {
		this.scene = scene;
	}

	public String getCustomsCode() {
		return this.customsCode;
	}

	public void setCustomsCode(String customsCode) {
		this.customsCode = customsCode;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getBusinessCode() {
		return this.businessCode;
	}

	public void setBusinessCode(String businessCode) {
		this.businessCode = businessCode;
	}

	public String getHitDesc() {
		return this.hitDesc;
	}

	public void setHitDesc(String hitDesc) {
		this.hitDesc = hitDesc;
	}

	public String getPositionDesc() {
		return this.positionDesc;
	}

	public void setPositionDesc(String positionDesc) {
		this.positionDesc = positionDesc;
	}

	public String getEntityKeys() {
		return this.entityKeys;
	}

	public void setEntityKeys(String entityKeys) {
		this.entityKeys = entityKeys;
	}

}
