package gov.customs.rule.data;

// Generated Aug 6, 2015 1:59:26 PM by Hibernate Tools 3.4.0.CR1

/**
 * RuleDomain generated by hbm2java
 */
public class RuleDomain implements java.io.Serializable {

	private long id;
	private String code;
	private String name;

	public RuleDomain() {
	}

	public RuleDomain(long id) {
		this.id = id;
	}

	public RuleDomain(long id, String code, String name) {
		this.id = id;
		this.code = code;
		this.name = name;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
