package gov.customs.rule.data;

// Generated Aug 6, 2015 1:59:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * RuleUserfunction generated by hbm2java
 */
public class RuleUserfunction implements java.io.Serializable {

	private BigDecimal id;
	private String functionType;
	private String functionSyntax;
	private String funcitonDesc;
	private String functionSample;

	public RuleUserfunction() {
	}

	public RuleUserfunction(BigDecimal id) {
		this.id = id;
	}

	public RuleUserfunction(BigDecimal id, String functionType,
			String functionSyntax, String funcitonDesc, String functionSample) {
		this.id = id;
		this.functionType = functionType;
		this.functionSyntax = functionSyntax;
		this.funcitonDesc = funcitonDesc;
		this.functionSample = functionSample;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getFunctionType() {
		return this.functionType;
	}

	public void setFunctionType(String functionType) {
		this.functionType = functionType;
	}

	public String getFunctionSyntax() {
		return this.functionSyntax;
	}

	public void setFunctionSyntax(String functionSyntax) {
		this.functionSyntax = functionSyntax;
	}

	public String getFuncitonDesc() {
		return this.funcitonDesc;
	}

	public void setFuncitonDesc(String funcitonDesc) {
		this.funcitonDesc = funcitonDesc;
	}

	public String getFunctionSample() {
		return this.functionSample;
	}

	public void setFunctionSample(String functionSample) {
		this.functionSample = functionSample;
	}

}
