package gov.customs.jm.data;

// Generated Jul 8, 2015 9:23:16 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * BhlHead generated by hbm2java
 */
public class BhlHead implements java.io.Serializable {

	private String bhlNo;
	private String eportNo;
	private String declareType;
	private String exEmsNo;
	private String exCopEmsNo;
	private String exCustomsCode;
	private String exTradeCode;
	private String exTradeName;
	private String exDeclareCode;
	private String exDeclareName;
	private String exCorpEr;
	private String exDeclareEr;
	private String exDistrictCode;
	private String exNote;
	private Date exDeclareDate;
	private String exChkEr;
	private Date exChkModDate;
	private Date exChkNewDate;
	private String exChkNote;
	private String exDeclCo;
	private String exDataSource;
	private String imEmsNo;
	private String imCopEmsNo;
	private String imCustomsCode;
	private String imTradeCode;
	private String imTradeName;
	private String imDeclareCode;
	private String imDeclareName;
	private String imCorpEr;
	private String imDeclareEr;
	private String imDistrictCode;
	private String imNote;
	private Date imDeclareDate;
	private String imChkEr;
	private Date imChkModDate;
	private Date imChkNewDate;
	private String imChkNote;
	private String imDeclCo;
	private String imDataSource;
	private BigDecimal intendCostTime;
	private BigDecimal distance;
	private String chkMark;
	private String exeMark;
	private String pauseMark;
	private Date endDate;
	private String col1;
	private BigDecimal col2;
	private Date col3;

	public BhlHead() {
	}

	public BhlHead(String bhlNo) {
		this.bhlNo = bhlNo;
	}

	public BhlHead(String bhlNo, String eportNo, String declareType,
			String exEmsNo, String exCopEmsNo, String exCustomsCode,
			String exTradeCode, String exTradeName, String exDeclareCode,
			String exDeclareName, String exCorpEr, String exDeclareEr,
			String exDistrictCode, String exNote, Date exDeclareDate,
			String exChkEr, Date exChkModDate, Date exChkNewDate,
			String exChkNote, String exDeclCo, String exDataSource,
			String imEmsNo, String imCopEmsNo, String imCustomsCode,
			String imTradeCode, String imTradeName, String imDeclareCode,
			String imDeclareName, String imCorpEr, String imDeclareEr,
			String imDistrictCode, String imNote, Date imDeclareDate,
			String imChkEr, Date imChkModDate, Date imChkNewDate,
			String imChkNote, String imDeclCo, String imDataSource,
			BigDecimal intendCostTime, BigDecimal distance, String chkMark,
			String exeMark, String pauseMark, Date endDate, String col1,
			BigDecimal col2, Date col3) {
		this.bhlNo = bhlNo;
		this.eportNo = eportNo;
		this.declareType = declareType;
		this.exEmsNo = exEmsNo;
		this.exCopEmsNo = exCopEmsNo;
		this.exCustomsCode = exCustomsCode;
		this.exTradeCode = exTradeCode;
		this.exTradeName = exTradeName;
		this.exDeclareCode = exDeclareCode;
		this.exDeclareName = exDeclareName;
		this.exCorpEr = exCorpEr;
		this.exDeclareEr = exDeclareEr;
		this.exDistrictCode = exDistrictCode;
		this.exNote = exNote;
		this.exDeclareDate = exDeclareDate;
		this.exChkEr = exChkEr;
		this.exChkModDate = exChkModDate;
		this.exChkNewDate = exChkNewDate;
		this.exChkNote = exChkNote;
		this.exDeclCo = exDeclCo;
		this.exDataSource = exDataSource;
		this.imEmsNo = imEmsNo;
		this.imCopEmsNo = imCopEmsNo;
		this.imCustomsCode = imCustomsCode;
		this.imTradeCode = imTradeCode;
		this.imTradeName = imTradeName;
		this.imDeclareCode = imDeclareCode;
		this.imDeclareName = imDeclareName;
		this.imCorpEr = imCorpEr;
		this.imDeclareEr = imDeclareEr;
		this.imDistrictCode = imDistrictCode;
		this.imNote = imNote;
		this.imDeclareDate = imDeclareDate;
		this.imChkEr = imChkEr;
		this.imChkModDate = imChkModDate;
		this.imChkNewDate = imChkNewDate;
		this.imChkNote = imChkNote;
		this.imDeclCo = imDeclCo;
		this.imDataSource = imDataSource;
		this.intendCostTime = intendCostTime;
		this.distance = distance;
		this.chkMark = chkMark;
		this.exeMark = exeMark;
		this.pauseMark = pauseMark;
		this.endDate = endDate;
		this.col1 = col1;
		this.col2 = col2;
		this.col3 = col3;
	}

	public String getBhlNo() {
		return this.bhlNo;
	}

	public void setBhlNo(String bhlNo) {
		this.bhlNo = bhlNo;
	}

	public String getEportNo() {
		return this.eportNo;
	}

	public void setEportNo(String eportNo) {
		this.eportNo = eportNo;
	}

	public String getDeclareType() {
		return this.declareType;
	}

	public void setDeclareType(String declareType) {
		this.declareType = declareType;
	}

	public String getExEmsNo() {
		return this.exEmsNo;
	}

	public void setExEmsNo(String exEmsNo) {
		this.exEmsNo = exEmsNo;
	}

	public String getExCopEmsNo() {
		return this.exCopEmsNo;
	}

	public void setExCopEmsNo(String exCopEmsNo) {
		this.exCopEmsNo = exCopEmsNo;
	}

	public String getExCustomsCode() {
		return this.exCustomsCode;
	}

	public void setExCustomsCode(String exCustomsCode) {
		this.exCustomsCode = exCustomsCode;
	}

	public String getExTradeCode() {
		return this.exTradeCode;
	}

	public void setExTradeCode(String exTradeCode) {
		this.exTradeCode = exTradeCode;
	}

	public String getExTradeName() {
		return this.exTradeName;
	}

	public void setExTradeName(String exTradeName) {
		this.exTradeName = exTradeName;
	}

	public String getExDeclareCode() {
		return this.exDeclareCode;
	}

	public void setExDeclareCode(String exDeclareCode) {
		this.exDeclareCode = exDeclareCode;
	}

	public String getExDeclareName() {
		return this.exDeclareName;
	}

	public void setExDeclareName(String exDeclareName) {
		this.exDeclareName = exDeclareName;
	}

	public String getExCorpEr() {
		return this.exCorpEr;
	}

	public void setExCorpEr(String exCorpEr) {
		this.exCorpEr = exCorpEr;
	}

	public String getExDeclareEr() {
		return this.exDeclareEr;
	}

	public void setExDeclareEr(String exDeclareEr) {
		this.exDeclareEr = exDeclareEr;
	}

	public String getExDistrictCode() {
		return this.exDistrictCode;
	}

	public void setExDistrictCode(String exDistrictCode) {
		this.exDistrictCode = exDistrictCode;
	}

	public String getExNote() {
		return this.exNote;
	}

	public void setExNote(String exNote) {
		this.exNote = exNote;
	}

	public Date getExDeclareDate() {
		return this.exDeclareDate;
	}

	public void setExDeclareDate(Date exDeclareDate) {
		this.exDeclareDate = exDeclareDate;
	}

	public String getExChkEr() {
		return this.exChkEr;
	}

	public void setExChkEr(String exChkEr) {
		this.exChkEr = exChkEr;
	}

	public Date getExChkModDate() {
		return this.exChkModDate;
	}

	public void setExChkModDate(Date exChkModDate) {
		this.exChkModDate = exChkModDate;
	}

	public Date getExChkNewDate() {
		return this.exChkNewDate;
	}

	public void setExChkNewDate(Date exChkNewDate) {
		this.exChkNewDate = exChkNewDate;
	}

	public String getExChkNote() {
		return this.exChkNote;
	}

	public void setExChkNote(String exChkNote) {
		this.exChkNote = exChkNote;
	}

	public String getExDeclCo() {
		return this.exDeclCo;
	}

	public void setExDeclCo(String exDeclCo) {
		this.exDeclCo = exDeclCo;
	}

	public String getExDataSource() {
		return this.exDataSource;
	}

	public void setExDataSource(String exDataSource) {
		this.exDataSource = exDataSource;
	}

	public String getImEmsNo() {
		return this.imEmsNo;
	}

	public void setImEmsNo(String imEmsNo) {
		this.imEmsNo = imEmsNo;
	}

	public String getImCopEmsNo() {
		return this.imCopEmsNo;
	}

	public void setImCopEmsNo(String imCopEmsNo) {
		this.imCopEmsNo = imCopEmsNo;
	}

	public String getImCustomsCode() {
		return this.imCustomsCode;
	}

	public void setImCustomsCode(String imCustomsCode) {
		this.imCustomsCode = imCustomsCode;
	}

	public String getImTradeCode() {
		return this.imTradeCode;
	}

	public void setImTradeCode(String imTradeCode) {
		this.imTradeCode = imTradeCode;
	}

	public String getImTradeName() {
		return this.imTradeName;
	}

	public void setImTradeName(String imTradeName) {
		this.imTradeName = imTradeName;
	}

	public String getImDeclareCode() {
		return this.imDeclareCode;
	}

	public void setImDeclareCode(String imDeclareCode) {
		this.imDeclareCode = imDeclareCode;
	}

	public String getImDeclareName() {
		return this.imDeclareName;
	}

	public void setImDeclareName(String imDeclareName) {
		this.imDeclareName = imDeclareName;
	}

	public String getImCorpEr() {
		return this.imCorpEr;
	}

	public void setImCorpEr(String imCorpEr) {
		this.imCorpEr = imCorpEr;
	}

	public String getImDeclareEr() {
		return this.imDeclareEr;
	}

	public void setImDeclareEr(String imDeclareEr) {
		this.imDeclareEr = imDeclareEr;
	}

	public String getImDistrictCode() {
		return this.imDistrictCode;
	}

	public void setImDistrictCode(String imDistrictCode) {
		this.imDistrictCode = imDistrictCode;
	}

	public String getImNote() {
		return this.imNote;
	}

	public void setImNote(String imNote) {
		this.imNote = imNote;
	}

	public Date getImDeclareDate() {
		return this.imDeclareDate;
	}

	public void setImDeclareDate(Date imDeclareDate) {
		this.imDeclareDate = imDeclareDate;
	}

	public String getImChkEr() {
		return this.imChkEr;
	}

	public void setImChkEr(String imChkEr) {
		this.imChkEr = imChkEr;
	}

	public Date getImChkModDate() {
		return this.imChkModDate;
	}

	public void setImChkModDate(Date imChkModDate) {
		this.imChkModDate = imChkModDate;
	}

	public Date getImChkNewDate() {
		return this.imChkNewDate;
	}

	public void setImChkNewDate(Date imChkNewDate) {
		this.imChkNewDate = imChkNewDate;
	}

	public String getImChkNote() {
		return this.imChkNote;
	}

	public void setImChkNote(String imChkNote) {
		this.imChkNote = imChkNote;
	}

	public String getImDeclCo() {
		return this.imDeclCo;
	}

	public void setImDeclCo(String imDeclCo) {
		this.imDeclCo = imDeclCo;
	}

	public String getImDataSource() {
		return this.imDataSource;
	}

	public void setImDataSource(String imDataSource) {
		this.imDataSource = imDataSource;
	}

	public BigDecimal getIntendCostTime() {
		return this.intendCostTime;
	}

	public void setIntendCostTime(BigDecimal intendCostTime) {
		this.intendCostTime = intendCostTime;
	}

	public BigDecimal getDistance() {
		return this.distance;
	}

	public void setDistance(BigDecimal distance) {
		this.distance = distance;
	}

	public String getChkMark() {
		return this.chkMark;
	}

	public void setChkMark(String chkMark) {
		this.chkMark = chkMark;
	}

	public String getExeMark() {
		return this.exeMark;
	}

	public void setExeMark(String exeMark) {
		this.exeMark = exeMark;
	}

	public String getPauseMark() {
		return this.pauseMark;
	}

	public void setPauseMark(String pauseMark) {
		this.pauseMark = pauseMark;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getCol1() {
		return this.col1;
	}

	public void setCol1(String col1) {
		this.col1 = col1;
	}

	public BigDecimal getCol2() {
		return this.col2;
	}

	public void setCol2(BigDecimal col2) {
		this.col2 = col2;
	}

	public Date getCol3() {
		return this.col3;
	}

	public void setCol3(Date col3) {
		this.col3 = col3;
	}

}
