package gov.customs.jm.data;

// Generated Jul 8, 2015 9:23:16 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * BhlListId generated by hbm2java
 */
public class BhlListId implements java.io.Serializable {

	private String bhlNo;
	private String GType;
	private BigDecimal GNo;

	public BhlListId() {
	}

	public BhlListId(String bhlNo, String GType, BigDecimal GNo) {
		this.bhlNo = bhlNo;
		this.GType = GType;
		this.GNo = GNo;
	}

	public String getBhlNo() {
		return this.bhlNo;
	}

	public void setBhlNo(String bhlNo) {
		this.bhlNo = bhlNo;
	}

	public String getGType() {
		return this.GType;
	}

	public void setGType(String GType) {
		this.GType = GType;
	}

	public BigDecimal getGNo() {
		return this.GNo;
	}

	public void setGNo(BigDecimal GNo) {
		this.GNo = GNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BhlListId))
			return false;
		BhlListId castOther = (BhlListId) other;

		return ((this.getBhlNo() == castOther.getBhlNo()) || (this.getBhlNo() != null
				&& castOther.getBhlNo() != null && this.getBhlNo().equals(
				castOther.getBhlNo())))
				&& ((this.getGType() == castOther.getGType()) || (this
						.getGType() != null && castOther.getGType() != null && this
						.getGType().equals(castOther.getGType())))
				&& ((this.getGNo() == castOther.getGNo()) || (this.getGNo() != null
						&& castOther.getGNo() != null && this.getGNo().equals(
						castOther.getGNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getBhlNo() == null ? 0 : this.getBhlNo().hashCode());
		result = 37 * result
				+ (getGType() == null ? 0 : this.getGType().hashCode());
		result = 37 * result
				+ (getGNo() == null ? 0 : this.getGNo().hashCode());
		return result;
	}

}
