package gov.customs.jm.data;

// Generated Jul 8, 2015 9:23:16 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * PreBhlList generated by hbm2java
 */
public class PreBhlList implements java.io.Serializable {

	private PreBhlListId id;
	private String eportNo;
	private BigDecimal emsGNo;
	private String codeTs;
	private String GName;
	private String GModel;
	private String unit;
	private BigDecimal qty;
	private String unit1;
	private BigDecimal qty1;
	private BigDecimal factQty;
	private BigDecimal factCount;
	private BigDecimal deductQty;
	private Date deductDate;
	private Date billImExDate;
	private String GMark;
	private String GNote;
	private String modifyMark;
	private Date createTime;
	private BigDecimal col1;
	private Date col2;
	private String col3;
	private String col4;
	private String col5;

	public PreBhlList() {
	}

	public PreBhlList(PreBhlListId id) {
		this.id = id;
	}

	public PreBhlList(PreBhlListId id, String eportNo, BigDecimal emsGNo,
			String codeTs, String GName, String GModel, String unit,
			BigDecimal qty, String unit1, BigDecimal qty1, BigDecimal factQty,
			BigDecimal factCount, BigDecimal deductQty, Date deductDate,
			Date billImExDate, String GMark, String GNote, String modifyMark,
			Date createTime, BigDecimal col1, Date col2, String col3,
			String col4, String col5) {
		this.id = id;
		this.eportNo = eportNo;
		this.emsGNo = emsGNo;
		this.codeTs = codeTs;
		this.GName = GName;
		this.GModel = GModel;
		this.unit = unit;
		this.qty = qty;
		this.unit1 = unit1;
		this.qty1 = qty1;
		this.factQty = factQty;
		this.factCount = factCount;
		this.deductQty = deductQty;
		this.deductDate = deductDate;
		this.billImExDate = billImExDate;
		this.GMark = GMark;
		this.GNote = GNote;
		this.modifyMark = modifyMark;
		this.createTime = createTime;
		this.col1 = col1;
		this.col2 = col2;
		this.col3 = col3;
		this.col4 = col4;
		this.col5 = col5;
	}

	public PreBhlListId getId() {
		return this.id;
	}

	public void setId(PreBhlListId id) {
		this.id = id;
	}

	public String getEportNo() {
		return this.eportNo;
	}

	public void setEportNo(String eportNo) {
		this.eportNo = eportNo;
	}

	public BigDecimal getEmsGNo() {
		return this.emsGNo;
	}

	public void setEmsGNo(BigDecimal emsGNo) {
		this.emsGNo = emsGNo;
	}

	public String getCodeTs() {
		return this.codeTs;
	}

	public void setCodeTs(String codeTs) {
		this.codeTs = codeTs;
	}

	public String getGName() {
		return this.GName;
	}

	public void setGName(String GName) {
		this.GName = GName;
	}

	public String getGModel() {
		return this.GModel;
	}

	public void setGModel(String GModel) {
		this.GModel = GModel;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	public String getUnit1() {
		return this.unit1;
	}

	public void setUnit1(String unit1) {
		this.unit1 = unit1;
	}

	public BigDecimal getQty1() {
		return this.qty1;
	}

	public void setQty1(BigDecimal qty1) {
		this.qty1 = qty1;
	}

	public BigDecimal getFactQty() {
		return this.factQty;
	}

	public void setFactQty(BigDecimal factQty) {
		this.factQty = factQty;
	}

	public BigDecimal getFactCount() {
		return this.factCount;
	}

	public void setFactCount(BigDecimal factCount) {
		this.factCount = factCount;
	}

	public BigDecimal getDeductQty() {
		return this.deductQty;
	}

	public void setDeductQty(BigDecimal deductQty) {
		this.deductQty = deductQty;
	}

	public Date getDeductDate() {
		return this.deductDate;
	}

	public void setDeductDate(Date deductDate) {
		this.deductDate = deductDate;
	}

	public Date getBillImExDate() {
		return this.billImExDate;
	}

	public void setBillImExDate(Date billImExDate) {
		this.billImExDate = billImExDate;
	}

	public String getGMark() {
		return this.GMark;
	}

	public void setGMark(String GMark) {
		this.GMark = GMark;
	}

	public String getGNote() {
		return this.GNote;
	}

	public void setGNote(String GNote) {
		this.GNote = GNote;
	}

	public String getModifyMark() {
		return this.modifyMark;
	}

	public void setModifyMark(String modifyMark) {
		this.modifyMark = modifyMark;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public BigDecimal getCol1() {
		return this.col1;
	}

	public void setCol1(BigDecimal col1) {
		this.col1 = col1;
	}

	public Date getCol2() {
		return this.col2;
	}

	public void setCol2(Date col2) {
		this.col2 = col2;
	}

	public String getCol3() {
		return this.col3;
	}

	public void setCol3(String col3) {
		this.col3 = col3;
	}

	public String getCol4() {
		return this.col4;
	}

	public void setCol4(String col4) {
		this.col4 = col4;
	}

	public String getCol5() {
		return this.col5;
	}

	public void setCol5(String col5) {
		this.col5 = col5;
	}

}
