package gov.customs.jm.data;

// Generated Jul 8, 2015 9:23:16 AM by Hibernate Tools 3.4.0.CR1

/**
 * RuleEntityMapping generated by hbm2java
 */
public class RuleEntityMapping implements java.io.Serializable {

	private long id;
	private String key;
	private String name;
	private String classFullname;
	private Long subsystem;
	private Long jarId;

	public RuleEntityMapping() {
	}

	public RuleEntityMapping(long id) {
		this.id = id;
	}

	public RuleEntityMapping(long id, String key, String name,
			String classFullname, Long subsystem, Long jarId) {
		this.id = id;
		this.key = key;
		this.name = name;
		this.classFullname = classFullname;
		this.subsystem = subsystem;
		this.jarId = jarId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getClassFullname() {
		return this.classFullname;
	}

	public void setClassFullname(String classFullname) {
		this.classFullname = classFullname;
	}

	public Long getSubsystem() {
		return this.subsystem;
	}

	public void setSubsystem(Long subsystem) {
		this.subsystem = subsystem;
	}

	public Long getJarId() {
		return this.jarId;
	}

	public void setJarId(Long jarId) {
		this.jarId = jarId;
	}

}
